tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_code_sniffer:
        config:
            standard: PSR2
    php_changetracking: true
    php_cs_fixer:
        config: { level: psr2 }
    php_mess_detector: true
    sensiolabs_security_checker: true
    external_code_coverage:
        timeout: 600
filter:
    excluded_paths:
        - 'tests/*'
        - 'examples/*'

checks:
    php:
        code_rating: true
        duplication: true
